
# Site settings
title: Jekyll Foobar Blog
email: puneet97.goyal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog detailing my experience as an intern at Avanti in the summer of '17.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #
github_username:  puneet97

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
